% Generates a clean equation image for constrained control allocation.
% Output: ../assets/constrained_allocation_equation.png

clear; close all; clc;

scriptDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(scriptDir);
assetDir = fullfile(repoRoot, 'assets');

if ~exist(assetDir, 'dir')
    mkdir(assetDir);
end

outFile = fullfile(assetDir, 'constrained_allocation_equation.png');

fig = figure('Color', 'w', ...
    'Units', 'pixels', ...
    'Position', [100 100 1500 560], ...
    'Visible', 'off');

ax = axes(fig, 'Position', [0 0 1 1]);
axis(ax, 'off');
xlim(ax, [0 1]);
ylim(ax, [0 1]);

navy = [0.05 0.14 0.25];
red = [0.70 0.16 0.13];
gray = [0.20 0.20 0.20];

text(ax, 0.5, 0.86, 'Constrained reallocation (not naive clipping)', ...
    'HorizontalAlignment', 'center', ...
    'FontName', 'Arial', ...
    'FontWeight', 'bold', ...
    'FontSize', 26, ...
    'Color', navy);

text(ax, 0.5, 0.60, ...
    '$T^\star = \arg\min_T \left\| W_u\,(B\,T-u_{\mathrm{cmd}}) \right\|_2^2 + \rho \left\|T-T_{\mathrm{trim}}\right\|_2^2$', ...
    'Interpreter', 'latex', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontSize', 28, ...
    'Color', navy, ...
    'Clipping', 'off');

text(ax, 0.5, 0.39, ...
    '$\mathrm{subject\ to}\quad 0 \leq T_i \leq T_{\max}$', ...
    'Interpreter', 'latex', ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontSize', 25, ...
    'Color', gray, ...
    'Clipping', 'off');

text(ax, 0.5, 0.22, ...
    'Weighted best-achievable command: prioritize force/moment errors instead of clipping each rotor independently.', ...
    'HorizontalAlignment', 'center', ...
    'FontName', 'Arial', ...
    'FontWeight', 'bold', ...
    'FontSize', 17, ...
    'Color', red);

print(fig, outFile, '-dpng', '-r220');
close(fig);

fprintf('Saved: %s\n', outFile);
